apiVersion: v1
kind: Service
metadata:
  name: coredns-lb-svc-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      
---

apiVersion: v1
kind: Service
metadata:
  name: coredns-lb-svc-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53