apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-admin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-view
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
