expose:
  type: ingress
  tls:
    enables: true
    secretName: harbor.34.123.29.105.nip.io
  ingress:
    hosts:
      core: harbor.34.123.29.105.nip.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
notary:
  enabled: false