apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    email: james@limaksvell.ru
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
      - http01:
          ingress:
            class: nginx

#---
#
#apiVersion: cert-manager.io/v1alpha2
#kind: Certificate
#metadata:
#  name: le-crt
#spec:
#  secretName: tls-secret
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-stage
#  commonName: yet-another.website
#  dnsNames:
#  - yet-another.website